// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaTecnico.Data;

#nullable disable

namespace SistemaTecnico.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922191854_gestionIncidencias")]
    partial class gestionIncidencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaTecnico.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Asistencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Remota"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Presencial"
                        });
                });

            modelBuilder.Entity("SistemaTecnico.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("AddressShipToCode")
                        .HasColumnType("text");

                    b.Property<int>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NroCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Destinos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Farmacia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Droguería"
                        });
                });

            modelBuilder.Entity("SistemaTecnico.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InnerException")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .HasColumnType("text");

                    b.Property<string>("Metodo")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("SistemaTecnico.Models.EstadoIncidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadosIncidencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Finalizado"
                        });
                });

            modelBuilder.Entity("SistemaTecnico.Models.EstadoPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoPresupuesto");
                });

            modelBuilder.Entity("SistemaTecnico.Models.EstadoTrabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadosTrabajo");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Tamanio")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsistenciaId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoIncidenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Otro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TareaId")
                        .HasColumnType("integer");

                    b.Property<string>("TrabajoRealizado")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("UsuarioFinalizadoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsistenciaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("EstadoIncidenciaId");

                    b.HasIndex("Fecha");

                    b.HasIndex("TareaId");

                    b.HasIndex("UsuarioFinalizadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("text");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioDecisionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TrabajoId");

                    b.HasIndex("UsuarioDecisionId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Soporte")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Comentarios")
                        .HasColumnType("text");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFinalizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPagado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Materiales")
                        .HasColumnType("text");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.Property<int>("TareaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("integer");

                    b.Property<string>("TecnicosAsignados")
                        .HasColumnType("text");

                    b.Property<string>("TrabajoRealizado")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SectorId");

                    b.HasIndex("TareaId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Trabajos");
                });

            modelBuilder.Entity("SistemaTecnico.Models.TrabajoFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPagado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId");

                    b.ToTable("TrabajoFacturas");
                });

            modelBuilder.Entity("SistemaTecnico.Models.TrabajoImagenComparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ImagenAntesId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImagenDespuesId")
                        .HasColumnType("integer");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImagenAntesId");

                    b.HasIndex("ImagenDespuesId");

                    b.HasIndex("TrabajoId");

                    b.ToTable("TrabajoImagenComparaciones");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CiudadId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NombreApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroCelular")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Ciudad", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Provincia", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Cliente", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Imagen", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Trabajo", "Trabajo")
                        .WithMany("SolicitudImagenes")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Incidencia", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Asistencia", "Asistencia")
                        .WithMany()
                        .HasForeignKey("AsistenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.EstadoIncidencia", "EstadoIncidencia")
                        .WithMany()
                        .HasForeignKey("EstadoIncidenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Usuario", "UsuarioFinalizado")
                        .WithMany()
                        .HasForeignKey("UsuarioFinalizadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTecnico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistencia");

                    b.Navigation("Cliente");

                    b.Navigation("Destino");

                    b.Navigation("EstadoIncidencia");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioFinalizado");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Presupuesto", b =>
                {
                    b.HasOne("SistemaTecnico.Models.EstadoPresupuesto", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Trabajo", "Trabajo")
                        .WithMany()
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Usuario", "UsuarioDecision")
                        .WithMany()
                        .HasForeignKey("UsuarioDecisionId");

                    b.Navigation("Estado");

                    b.Navigation("Tecnico");

                    b.Navigation("Trabajo");

                    b.Navigation("UsuarioDecision");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Sector", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Tarea", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Trabajo", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Cliente", "Cliente")
                        .WithMany("Trabajos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.EstadoTrabajo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Usuario", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTecnico.Models.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Sector");

                    b.Navigation("Tarea");

                    b.Navigation("Tecnico");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("SistemaTecnico.Models.TrabajoFactura", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Trabajo", "Trabajo")
                        .WithMany("Facturas")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("SistemaTecnico.Models.TrabajoImagenComparacion", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Imagen", "ImagenAntes")
                        .WithMany()
                        .HasForeignKey("ImagenAntesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTecnico.Models.Imagen", "ImagenDespues")
                        .WithMany()
                        .HasForeignKey("ImagenDespuesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTecnico.Models.Trabajo", "Trabajo")
                        .WithMany("ComparacionesImagenes")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImagenAntes");

                    b.Navigation("ImagenDespues");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Usuario", b =>
                {
                    b.HasOne("SistemaTecnico.Models.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId");

                    b.HasOne("SistemaTecnico.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SistemaTecnico.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTecnico.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId");

                    b.Navigation("Ciudad");

                    b.Navigation("Cliente");

                    b.Navigation("Perfil");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Cliente", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Provincia", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("SistemaTecnico.Models.Trabajo", b =>
                {
                    b.Navigation("ComparacionesImagenes");

                    b.Navigation("Facturas");

                    b.Navigation("SolicitudImagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
