CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ErrorLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fecha" timestamp with time zone NOT NULL,
    "Mensaje" text,
    "StackTrace" text,
    "InnerException" text,
    "Endpoint" text,
    "Metodo" text,
    "Usuario" text,
    "Ip" text,
    CONSTRAINT "PK_ErrorLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "EstadoPresupuesto" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_EstadoPresupuesto" PRIMARY KEY ("Id")
);

CREATE TABLE "EstadosTrabajo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Color" text NOT NULL,
    CONSTRAINT "PK_EstadosTrabajo" PRIMARY KEY ("Id")
);

CREATE TABLE "Perfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Perfiles" PRIMARY KEY ("Id")
);

CREATE TABLE "Provincias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Provincias" PRIMARY KEY ("Id")
);

CREATE TABLE "Sectores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "PerfilId" integer NOT NULL,
    CONSTRAINT "PK_Sectores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sectores_Perfiles_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfiles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Ciudades" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "ProvinciaId" integer NOT NULL,
    CONSTRAINT "PK_Ciudades" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Ciudades_Provincias_ProvinciaId" FOREIGN KEY ("ProvinciaId") REFERENCES "Provincias" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Tareas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" text NOT NULL,
    "SectorId" integer NOT NULL,
    CONSTRAINT "PK_Tareas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tareas_Sectores_SectorId" FOREIGN KEY ("SectorId") REFERENCES "Sectores" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Clientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NroCliente" text NOT NULL,
    "Nombre" text NOT NULL,
    "RazonSocial" text,
    "Direccion" text,
    "AddressShipToCode" text,
    "ProvinciaId" integer NOT NULL,
    "CiudadId" integer NOT NULL,
    "Email" text,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Clientes_Ciudades_CiudadId" FOREIGN KEY ("CiudadId") REFERENCES "Ciudades" ("Id"),
    CONSTRAINT "FK_Clientes_Provincias_ProvinciaId" FOREIGN KEY ("ProvinciaId") REFERENCES "Provincias" ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "NombreApellido" text NOT NULL,
    "Email" text,
    "NumeroCelular" text,
    "Activo" boolean NOT NULL,
    "PerfilId" integer NOT NULL,
    "ProvinciaId" integer,
    "CiudadId" integer,
    "ClienteId" integer,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Ciudades_CiudadId" FOREIGN KEY ("CiudadId") REFERENCES "Ciudades" ("Id"),
    CONSTRAINT "FK_Usuarios_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id"),
    CONSTRAINT "FK_Usuarios_Perfiles_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfiles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Usuarios_Provincias_ProvinciaId" FOREIGN KEY ("ProvinciaId") REFERENCES "Provincias" ("Id")
);

CREATE TABLE "Trabajos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaSolicitud" timestamp with time zone NOT NULL,
    "FechaInicio" timestamp with time zone,
    "FechaFinalizado" timestamp with time zone,
    "ClienteId" integer NOT NULL,
    "TecnicosAsignados" text,
    "TecnicoId" integer,
    "UsuarioCreacionId" integer NOT NULL,
    "EstadoId" integer NOT NULL,
    "SectorId" integer NOT NULL,
    "TareaId" integer NOT NULL,
    "Comentarios" text,
    "TrabajoRealizado" text,
    "Materiales" text,
    "FechaPagado" timestamp with time zone,
    CONSTRAINT "PK_Trabajos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Trabajos_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Trabajos_EstadosTrabajo_EstadoId" FOREIGN KEY ("EstadoId") REFERENCES "EstadosTrabajo" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Trabajos_Sectores_SectorId" FOREIGN KEY ("SectorId") REFERENCES "Sectores" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Trabajos_Tareas_TareaId" FOREIGN KEY ("TareaId") REFERENCES "Tareas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Trabajos_Usuarios_TecnicoId" FOREIGN KEY ("TecnicoId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Trabajos_Usuarios_UsuarioCreacionId" FOREIGN KEY ("UsuarioCreacionId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Imagenes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TrabajoId" integer NOT NULL,
    "Tipo" text NOT NULL,
    "NombreArchivo" text NOT NULL,
    "RutaArchivo" text NOT NULL,
    "Extension" text,
    "Tamanio" bigint NOT NULL,
    "FechaCarga" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Imagenes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Imagenes_Trabajos_TrabajoId" FOREIGN KEY ("TrabajoId") REFERENCES "Trabajos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Presupuestos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FechaCarga" timestamp with time zone NOT NULL,
    "TecnicoId" integer NOT NULL,
    "UsuarioDecisionId" integer,
    "FechaDecision" timestamp with time zone,
    "EstadoId" integer NOT NULL,
    "MotivoRechazo" text,
    "Descripcion" text,
    "RutaArchivo" text,
    "TrabajoId" integer NOT NULL,
    CONSTRAINT "PK_Presupuestos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Presupuestos_EstadoPresupuesto_EstadoId" FOREIGN KEY ("EstadoId") REFERENCES "EstadoPresupuesto" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Presupuestos_Trabajos_TrabajoId" FOREIGN KEY ("TrabajoId") REFERENCES "Trabajos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Presupuestos_Usuarios_TecnicoId" FOREIGN KEY ("TecnicoId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Presupuestos_Usuarios_UsuarioDecisionId" FOREIGN KEY ("UsuarioDecisionId") REFERENCES "Usuarios" ("Id")
);

CREATE TABLE "TrabajoFacturas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TrabajoId" integer NOT NULL,
    "RutaArchivo" text NOT NULL,
    "FechaCarga" timestamp with time zone NOT NULL,
    "FechaPagado" timestamp with time zone,
    CONSTRAINT "PK_TrabajoFacturas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TrabajoFacturas_Trabajos_TrabajoId" FOREIGN KEY ("TrabajoId") REFERENCES "Trabajos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TrabajoImagenComparaciones" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TrabajoId" integer NOT NULL,
    "ImagenAntesId" integer,
    "ImagenDespuesId" integer,
    CONSTRAINT "PK_TrabajoImagenComparaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TrabajoImagenComparaciones_Imagenes_ImagenAntesId" FOREIGN KEY ("ImagenAntesId") REFERENCES "Imagenes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TrabajoImagenComparaciones_Imagenes_ImagenDespuesId" FOREIGN KEY ("ImagenDespuesId") REFERENCES "Imagenes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TrabajoImagenComparaciones_Trabajos_TrabajoId" FOREIGN KEY ("TrabajoId") REFERENCES "Trabajos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Ciudades_ProvinciaId" ON "Ciudades" ("ProvinciaId");

CREATE INDEX "IX_Clientes_CiudadId" ON "Clientes" ("CiudadId");

CREATE INDEX "IX_Clientes_ProvinciaId" ON "Clientes" ("ProvinciaId");

CREATE INDEX "IX_Imagenes_TrabajoId" ON "Imagenes" ("TrabajoId");

CREATE INDEX "IX_Presupuestos_EstadoId" ON "Presupuestos" ("EstadoId");

CREATE INDEX "IX_Presupuestos_TecnicoId" ON "Presupuestos" ("TecnicoId");

CREATE INDEX "IX_Presupuestos_TrabajoId" ON "Presupuestos" ("TrabajoId");

CREATE INDEX "IX_Presupuestos_UsuarioDecisionId" ON "Presupuestos" ("UsuarioDecisionId");

CREATE INDEX "IX_Sectores_PerfilId" ON "Sectores" ("PerfilId");

CREATE INDEX "IX_Tareas_SectorId" ON "Tareas" ("SectorId");

CREATE INDEX "IX_TrabajoFacturas_TrabajoId" ON "TrabajoFacturas" ("TrabajoId");

CREATE INDEX "IX_TrabajoImagenComparaciones_ImagenAntesId" ON "TrabajoImagenComparaciones" ("ImagenAntesId");

CREATE INDEX "IX_TrabajoImagenComparaciones_ImagenDespuesId" ON "TrabajoImagenComparaciones" ("ImagenDespuesId");

CREATE INDEX "IX_TrabajoImagenComparaciones_TrabajoId" ON "TrabajoImagenComparaciones" ("TrabajoId");

CREATE INDEX "IX_Trabajos_ClienteId" ON "Trabajos" ("ClienteId");

CREATE INDEX "IX_Trabajos_EstadoId" ON "Trabajos" ("EstadoId");

CREATE INDEX "IX_Trabajos_SectorId" ON "Trabajos" ("SectorId");

CREATE INDEX "IX_Trabajos_TareaId" ON "Trabajos" ("TareaId");

CREATE INDEX "IX_Trabajos_TecnicoId" ON "Trabajos" ("TecnicoId");

CREATE INDEX "IX_Trabajos_UsuarioCreacionId" ON "Trabajos" ("UsuarioCreacionId");

CREATE INDEX "IX_Usuarios_CiudadId" ON "Usuarios" ("CiudadId");

CREATE INDEX "IX_Usuarios_ClienteId" ON "Usuarios" ("ClienteId");

CREATE INDEX "IX_Usuarios_PerfilId" ON "Usuarios" ("PerfilId");

CREATE INDEX "IX_Usuarios_ProvinciaId" ON "Usuarios" ("ProvinciaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260914134932_InitialPostgreSql', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Tareas" ADD "Soporte" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "Asistencias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Asistencias" PRIMARY KEY ("Id")
);

CREATE TABLE "Destinos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Destinos" PRIMARY KEY ("Id")
);

CREATE TABLE "EstadosIncidencia" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_EstadosIncidencia" PRIMARY KEY ("Id")
);

CREATE TABLE "Incidencias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "ClienteId" integer NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "DestinoId" integer NOT NULL,
    "TareaId" integer NOT NULL,
    "AsistenciaId" integer NOT NULL,
    "EstadoIncidenciaId" integer NOT NULL,
    "Otro" character varying(500),
    "TrabajoRealizado" character varying(4000),
    "UsuarioFinalizadoId" integer,
    "FechaFinalizado" timestamp with time zone,
    CONSTRAINT "PK_Incidencias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Incidencias_Asistencias_AsistenciaId" FOREIGN KEY ("AsistenciaId") REFERENCES "Asistencias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidencias_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidencias_Destinos_DestinoId" FOREIGN KEY ("DestinoId") REFERENCES "Destinos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidencias_EstadosIncidencia_EstadoIncidenciaId" FOREIGN KEY ("EstadoIncidenciaId") REFERENCES "EstadosIncidencia" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidencias_Tareas_TareaId" FOREIGN KEY ("TareaId") REFERENCES "Tareas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Incidencias_Usuarios_UsuarioFinalizadoId" FOREIGN KEY ("UsuarioFinalizadoId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Incidencias_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Asistencias" ("Id", "Nombre")
VALUES (1, 'Remota');
INSERT INTO "Asistencias" ("Id", "Nombre")
VALUES (2, 'Presencial');

INSERT INTO "Destinos" ("Id", "Nombre")
VALUES (1, 'Farmacia');
INSERT INTO "Destinos" ("Id", "Nombre")
VALUES (2, 'Droguería');

INSERT INTO "EstadosIncidencia" ("Id", "Nombre")
VALUES (1, 'Pendiente');
INSERT INTO "EstadosIncidencia" ("Id", "Nombre")
VALUES (2, 'Finalizado');

CREATE INDEX "IX_Incidencias_AsistenciaId" ON "Incidencias" ("AsistenciaId");

CREATE INDEX "IX_Incidencias_ClienteId" ON "Incidencias" ("ClienteId");

CREATE INDEX "IX_Incidencias_DestinoId" ON "Incidencias" ("DestinoId");

CREATE INDEX "IX_Incidencias_EstadoIncidenciaId" ON "Incidencias" ("EstadoIncidenciaId");

CREATE INDEX "IX_Incidencias_Fecha" ON "Incidencias" ("Fecha");

CREATE INDEX "IX_Incidencias_TareaId" ON "Incidencias" ("TareaId");

CREATE INDEX "IX_Incidencias_UsuarioFinalizadoId" ON "Incidencias" ("UsuarioFinalizadoId");

CREATE INDEX "IX_Incidencias_UsuarioId" ON "Incidencias" ("UsuarioId");

SELECT setval(
    pg_get_serial_sequence('"Asistencias"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Asistencias") + 1,
        nextval(pg_get_serial_sequence('"Asistencias"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Destinos"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Destinos") + 1,
        nextval(pg_get_serial_sequence('"Destinos"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"EstadosIncidencia"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "EstadosIncidencia") + 1,
        nextval(pg_get_serial_sequence('"EstadosIncidencia"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260922191854_gestionIncidencias', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Incidencias" ADD "Comentario" character varying(4000);

ALTER TABLE "Incidencias" ADD "Guardia" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260923120347_nuevosCamposIncidencia', '10.0.9');

COMMIT;

